// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("entity_analytics")
	ScopeName = "github.com/elastic/opentelemetry-collector-components/receiver/entityanalyticsreceiver"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
