---
version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    labels:
      - automation
    groups:
      otel-dependencies:
        patterns:
          - "go.opentelemetry.io/*"
          - "github.com/open-telemetry/opentelemetry-collector-contrib/*"
          - "github.com/elastic/opentelemetry-lib"
      non-otel:
        group-by: dependency-name
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - automation
