---
version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    labels:
      - automation
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/*"
          - "github.com/open-telemetry/opentelemetry-collector-contrib/*"
          - "github.com/elastic/opentelemetry-lib"
      aws:
        patterns:
          - "github.com/aws/*"
      prometheus:
        patterns:
          - "github.com/prometheus/*"
      golang-x:
        patterns:
          - "golang.org/x/*"
      kubernetes:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
      azure:
        patterns:
          - "github.com/Azure/*"
          - "github.com/AzureAD/*"
      google:
        patterns:
          - "cloud.google.com/go/*"
          - "google.golang.org/*"
          - "github.com/googleapis/*"
      other:
        group-by: dependency-name
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - automation
