receivers:
  filelog:
    include_file_name: true
    include:
      - "./otlp-all.json"

extensions:
  beatsauth: 
    tls:
      verification_mode: certificate

exporters:
  debug:
    verbosity: detailed
  elasticsearch: 
   endpoints: 
    -  https://localhost:9201
   tls:
    ## This ca does not have SAN or CN 
    ## The connection should work as we use verification:mode as certificate and we perform no hostname verification
    ca_file: /Users/khushijain/Documents/beats/testing/environments/docker/elasticsearch/pki/ca/ca.crt
   password: testing
   user: admin
  #  auth: 
  #   authenticator: beatsauth

service:
  extensions: [beatsauth]
  pipelines:
    logs:
      receivers: [filelog]
      processors: []
      exporters: [debug, elasticsearch]