// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("prometheusremotewrite")
	ScopeName = "github.com/elastic/opentelemetry-collector-components/receiver/prometheusremotewritev1receiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
