// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/component/componenttest"
	"go.opentelemetry.io/collector/connector"
	"go.opentelemetry.io/collector/connector/connectortest"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"
)

func NewSettings(tt *componenttest.Telemetry) connector.Settings {
	set := connectortest.NewNopSettings(connectortest.NopType)
	set.ID = component.NewID(component.MustNewType("dynamicrouting"))
	set.TelemetrySettings = tt.NewTelemetrySettings()
	return set
}

func AssertEqualDynamicroutingRouted(t *testing.T, tt *componenttest.Telemetry, dps []metricdata.DataPoint[int64], opts ...metricdatatest.Option) {
	want := metricdata.Metrics{
		Name:        "otelcol.dynamicrouting.routed",
		Description: "Number of telemetry batches routed by the connector. [Development]",
		Unit:        "1",
		Data: metricdata.Sum[int64]{
			Temporality: metricdata.CumulativeTemporality,
			IsMonotonic: true,
			DataPoints:  dps,
		},
	}
	got, err := tt.GetMetric("otelcol.dynamicrouting.routed")
	require.NoError(t, err)
	metricdatatest.AssertEqual(t, want, got, opts...)
}
