// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("certscanner")
	ScopeName = "github.com/elastic/opentelemetry-collector-components/receiver/certscannerreceiver"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
