// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("elasticapm")
	ScopeName = "github.com/elastic/opentelemetry-collector-components/connector/elasticapmconnector"
)

const (
	LogsToMetricsStability    = component.StabilityLevelDevelopment
	MetricsToMetricsStability = component.StabilityLevelDevelopment
	TracesToMetricsStability  = component.StabilityLevelDevelopment
)
