// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("ratelimit")
	ScopeName = "github.com/elastic/opentelemetry-collector-components/processor/ratelimitprocessor"
)

const (
	LogsStability     = component.StabilityLevelDevelopment
	TracesStability   = component.StabilityLevelDevelopment
	MetricsStability  = component.StabilityLevelDevelopment
	ProfilesStability = component.StabilityLevelDevelopment
)
