// ELASTICSEARCH CONFIDENTIAL
// __________________
//
//  Copyright Elasticsearch B.V. All rights reserved.
//
// NOTICE:  All information contained herein is, and remains
// the property of Elasticsearch B.V. and its suppliers, if any.
// The intellectual and technical concepts contained herein
// are proprietary to Elasticsearch B.V. and its suppliers and
// may be covered by U.S. and Foreign Patents, patents in
// process, and are protected by trade secret or copyright
// law.  Dissemination of this information or reproduction of
// this material is strictly forbidden unless prior written
// permission is obtained from Elasticsearch B.V.

// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("ratelimit")
	ScopeName = "github.com/elastic/opentelemetry-collector-components/processor/ratelimitprocessor"
)

const (
	LogsStability     = component.StabilityLevelDevelopment
	TracesStability   = component.StabilityLevelDevelopment
	MetricsStability  = component.StabilityLevelDevelopment
	ProfilesStability = component.StabilityLevelDevelopment
)
