// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("akamai_siem")
	ScopeName = "github.com/elastic/opentelemetry-collector-components/receiver/akamaisiemreceiver"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
