// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/elastic/opentelemetry-collector-components/receiver/akamaisiemreceiver")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/elastic/opentelemetry-collector-components/receiver/akamaisiemreceiver")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                             metric.Meter
	mu                                sync.Mutex
	registrations                     []metric.Registration
	AkamaiSiemBytesReceived           metric.Int64Counter
	AkamaiSiemCursorPersists          metric.Int64Counter
	AkamaiSiemEventsEmitted           metric.Int64Counter
	AkamaiSiemEventsPerPage           metric.Int64Histogram
	AkamaiSiemEventsPerSecond         metric.Float64Histogram
	AkamaiSiemEventsReceived          metric.Int64Counter
	AkamaiSiemInvalidTimestampRetries metric.Int64Counter
	AkamaiSiemOffsetExpired           metric.Int64Counter
	AkamaiSiemOffsetTTLDrops          metric.Int64Counter
	AkamaiSiemPageProcessingTime      metric.Float64Histogram
	AkamaiSiemPagesProcessed          metric.Int64Counter
	AkamaiSiemPollDuration            metric.Float64Histogram
	AkamaiSiemRecoveryAttempts        metric.Int64Counter
	AkamaiSiemRequestDuration         metric.Float64Histogram
	AkamaiSiemRequestErrors           metric.Int64Counter
	AkamaiSiemRequests                metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.AkamaiSiemBytesReceived, err = builder.meter.Int64Counter(
		"otelcol_akamai_siem.bytes_received",
		metric.WithDescription("Total bytes received from the Akamai SIEM API [Alpha]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	builder.AkamaiSiemCursorPersists, err = builder.meter.Int64Counter(
		"otelcol_akamai_siem.cursor_persists",
		metric.WithDescription("Total successful cursor persist operations [Alpha]"),
		metric.WithUnit("{persists}"),
	)
	errs = errors.Join(errs, err)
	builder.AkamaiSiemEventsEmitted, err = builder.meter.Int64Counter(
		"otelcol_akamai_siem.events_emitted",
		metric.WithDescription("Total events successfully forwarded to the downstream consumer via ConsumeLogs [Alpha]"),
		metric.WithUnit("{events}"),
	)
	errs = errors.Join(errs, err)
	builder.AkamaiSiemEventsPerPage, err = builder.meter.Int64Histogram(
		"otelcol_akamai_siem.events_per_page",
		metric.WithDescription("Number of events received per API response page [Alpha]"),
		metric.WithUnit("{events}"),
		metric.WithExplicitBucketBoundaries([]float64{0, 10, 50, 100, 500, 1000, 5000, 10000, 50000, 100000, 600000}...),
	)
	errs = errors.Join(errs, err)
	builder.AkamaiSiemEventsPerSecond, err = builder.meter.Float64Histogram(
		"otelcol_akamai_siem.events_per_second",
		metric.WithDescription("Events per second throughput per poll cycle [Alpha]"),
		metric.WithUnit("{events}/s"),
		metric.WithExplicitBucketBoundaries([]float64{100, 500, 1000, 5000, 10000, 25000, 50000, 100000, 500000}...),
	)
	errs = errors.Join(errs, err)
	builder.AkamaiSiemEventsReceived, err = builder.meter.Int64Counter(
		"otelcol_akamai_siem.events_received",
		metric.WithDescription("Total events received from the Akamai SIEM API [Alpha]"),
		metric.WithUnit("{events}"),
	)
	errs = errors.Join(errs, err)
	builder.AkamaiSiemInvalidTimestampRetries, err = builder.meter.Int64Counter(
		"otelcol_akamai_siem.invalid_timestamp_retries",
		metric.WithDescription("Total HMAC timestamp retries [Alpha]"),
		metric.WithUnit("{retries}"),
	)
	errs = errors.Join(errs, err)
	builder.AkamaiSiemOffsetExpired, err = builder.meter.Int64Counter(
		"otelcol_akamai_siem.offset_expired",
		metric.WithDescription("Total 416 offset out of range errors [Alpha]"),
		metric.WithUnit("{errors}"),
	)
	errs = errors.Join(errs, err)
	builder.AkamaiSiemOffsetTTLDrops, err = builder.meter.Int64Counter(
		"otelcol_akamai_siem.offset_ttl_drops",
		metric.WithDescription("Total proactive offset TTL expirations [Alpha]"),
		metric.WithUnit("{drops}"),
	)
	errs = errors.Join(errs, err)
	builder.AkamaiSiemPageProcessingTime, err = builder.meter.Float64Histogram(
		"otelcol_akamai_siem.page_processing_time",
		metric.WithDescription("Time to process a page (NDJSON parse + body-map construction + ConsumeLogs) [Alpha]"),
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries([]float64{0.001, 0.005, 0.01, 0.05, 0.1, 0.25, 0.5, 1, 5, 10}...),
	)
	errs = errors.Join(errs, err)
	builder.AkamaiSiemPagesProcessed, err = builder.meter.Int64Counter(
		"otelcol_akamai_siem.pages_processed",
		metric.WithDescription("Total API response pages processed [Alpha]"),
		metric.WithUnit("{pages}"),
	)
	errs = errors.Join(errs, err)
	builder.AkamaiSiemPollDuration, err = builder.meter.Float64Histogram(
		"otelcol_akamai_siem.poll_duration",
		metric.WithDescription("Duration of a full poll iteration (may include multiple pages) [Alpha]"),
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries([]float64{0.1, 0.5, 1, 5, 10, 30, 60, 120, 300}...),
	)
	errs = errors.Join(errs, err)
	builder.AkamaiSiemRecoveryAttempts, err = builder.meter.Int64Counter(
		"otelcol_akamai_siem.recovery_attempts",
		metric.WithDescription("Total recovery actions taken (416 replays, timestamp retries, from clamps) [Alpha]"),
		metric.WithUnit("{attempts}"),
	)
	errs = errors.Join(errs, err)
	builder.AkamaiSiemRequestDuration, err = builder.meter.Float64Histogram(
		"otelcol_akamai_siem.request_duration",
		metric.WithDescription("Duration of API requests to the Akamai SIEM API [Alpha]"),
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries([]float64{0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30, 60}...),
	)
	errs = errors.Join(errs, err)
	builder.AkamaiSiemRequestErrors, err = builder.meter.Int64Counter(
		"otelcol_akamai_siem.request_errors",
		metric.WithDescription("Total failed API requests (non-200 responses) [Alpha]"),
		metric.WithUnit("{requests}"),
	)
	errs = errors.Join(errs, err)
	builder.AkamaiSiemRequests, err = builder.meter.Int64Counter(
		"otelcol_akamai_siem.requests",
		metric.WithDescription("Total API requests made to the Akamai SIEM API [Alpha]"),
		metric.WithUnit("{requests}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
