// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("elastictrace")
	ScopeName = "github.com/elastic/opentelemetry-collector-components/processor/elastictraceprocessor"
)

const (
	TracesStability = component.StabilityLevelAlpha
)
