# Use this changelog template to create an entry for release notes.

# One of 'breaking', 'deprecation', 'enhancement', 'bug_fix'
change_type: breaking

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Use embedded collector config instead of searching for config.yaml in file system if `-config` is not specified

# It is mandatory to specify the component. Do not change this.
component: otelbench

# Mandatory: One or more tracking issues related to the change. You can use the PR number here if no issue exists.
issues: [615]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: Removes dependency on config.yaml being present in file system