# Use this changelog template to create an entry for release notes.

# One of 'breaking', 'deprecation', 'enhancement', 'bug_fix'
change_type: enhancement

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Add disable_pdata_reuse config to the loadgenreceiver.

# It is mandatory to specify the component. Do not change this.
component: otelbench

# Mandatory: One or more tracking issues related to the change. You can use the PR number here if no issue exists.
issues: [686]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: Add a config that fixes panic when batchprocessor is used.