// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"

	"github.com/elastic/opentelemetry-collector-components/receiver/akamaisiemreceiver/internal/metadata"
	"go.opentelemetry.io/collector/component/componenttest"
)

func TestSetupTelemetry(t *testing.T) {
	testTel := componenttest.NewTelemetry()
	tb, err := metadata.NewTelemetryBuilder(testTel.NewTelemetrySettings())
	require.NoError(t, err)
	defer tb.Shutdown()
	tb.AkamaiSiemBytesReceived.Add(context.Background(), 1)
	tb.AkamaiSiemCursorPersists.Add(context.Background(), 1)
	tb.AkamaiSiemEventsEmitted.Add(context.Background(), 1)
	tb.AkamaiSiemEventsPerPage.Record(context.Background(), 1)
	tb.AkamaiSiemEventsPerSecond.Record(context.Background(), 1)
	tb.AkamaiSiemEventsReceived.Add(context.Background(), 1)
	tb.AkamaiSiemInvalidTimestampRetries.Add(context.Background(), 1)
	tb.AkamaiSiemMappingDuration.Record(context.Background(), 1)
	tb.AkamaiSiemMappingErrors.Add(context.Background(), 1)
	tb.AkamaiSiemOffsetExpired.Add(context.Background(), 1)
	tb.AkamaiSiemOffsetTTLDrops.Add(context.Background(), 1)
	tb.AkamaiSiemPageProcessingTime.Record(context.Background(), 1)
	tb.AkamaiSiemPagesProcessed.Add(context.Background(), 1)
	tb.AkamaiSiemPollDuration.Record(context.Background(), 1)
	tb.AkamaiSiemRecoveryAttempts.Add(context.Background(), 1)
	tb.AkamaiSiemRequestDuration.Record(context.Background(), 1)
	tb.AkamaiSiemRequestErrors.Add(context.Background(), 1)
	tb.AkamaiSiemRequests.Add(context.Background(), 1)
	AssertEqualAkamaiSiemBytesReceived(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualAkamaiSiemCursorPersists(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualAkamaiSiemEventsEmitted(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualAkamaiSiemEventsPerPage(t, testTel,
		[]metricdata.HistogramDataPoint[int64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualAkamaiSiemEventsPerSecond(t, testTel,
		[]metricdata.HistogramDataPoint[float64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualAkamaiSiemEventsReceived(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualAkamaiSiemInvalidTimestampRetries(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualAkamaiSiemMappingDuration(t, testTel,
		[]metricdata.HistogramDataPoint[float64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualAkamaiSiemMappingErrors(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualAkamaiSiemOffsetExpired(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualAkamaiSiemOffsetTTLDrops(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualAkamaiSiemPageProcessingTime(t, testTel,
		[]metricdata.HistogramDataPoint[float64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualAkamaiSiemPagesProcessed(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualAkamaiSiemPollDuration(t, testTel,
		[]metricdata.HistogramDataPoint[float64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualAkamaiSiemRecoveryAttempts(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualAkamaiSiemRequestDuration(t, testTel,
		[]metricdata.HistogramDataPoint[float64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualAkamaiSiemRequestErrors(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualAkamaiSiemRequests(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())

	require.NoError(t, testTel.Shutdown(context.Background()))
}
