// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("beatsauth")
	ScopeName = "github.com/elastic/opentelemetry-collector-components/extension/beatsauthextension"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
