// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("config_integrations")
	ScopeName = "github.com/elastic/opentelemetry-collector-components/extension/configintegrationextension"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
