// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: tunnel.proto

package tunnelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientFrame flows collector -> relay.
type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// register is sent exactly once, as the very first frame.
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3" json:"register,omitempty"`
	// request_id correlates a result with a request the relay sent down the stream.
	RequestId string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// result_json is a JSON-marshaled ReadResult.
	ResultJson    []byte `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *ClientFrame) GetRegister() *Register {
	if x != nil {
		return x.Register
	}
	return nil
}

func (x *ClientFrame) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ClientFrame) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

// ServerFrame flows relay -> collector.
type ServerFrame struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// request_json is a JSON-marshaled ReadRequest.
	RequestJson   []byte `protobuf:"bytes,2,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *ServerFrame) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServerFrame) GetRequestJson() []byte {
	if x != nil {
		return x.RequestJson
	}
	return nil
}

// Register carries the identifying metadata used for discovery (GET /targets).
// Each registered collector is a "probe": an in-cluster, read-only investigative
// endpoint. "agent" is intentionally avoided here to leave that word for the
// external AI investigation agent.
type Register struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Token            string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                    // stubbed auth
	ProbeId          string                 `protobuf:"bytes,2,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"` // unique per collector (probe) instance
	ClusterId        string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeName         string                 `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	PodName          string                 `protobuf:"bytes,5,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace        string                 `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CollectorVersion string                 `protobuf:"bytes,7,opt,name=collector_version,json=collectorVersion,proto3" json:"collector_version,omitempty"`
	K8SVersion       string                 `protobuf:"bytes,8,opt,name=k8s_version,json=k8sVersion,proto3" json:"k8s_version,omitempty"`
	Labels           map[string]string      `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Register) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *Register) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Register) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Register) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *Register) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Register) GetCollectorVersion() string {
	if x != nil {
		return x.CollectorVersion
	}
	return ""
}

func (x *Register) GetK8SVersion() string {
	if x != nil {
		return x.K8SVersion
	}
	return ""
}

func (x *Register) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_tunnel_proto protoreflect.FileDescriptor

const file_tunnel_proto_rawDesc = "" +
	"\n" +
	"\ftunnel.proto\x12\rkubetunnel.v1\"\x82\x01\n" +
	"\vClientFrame\x123\n" +
	"\bregister\x18\x01 \x01(\v2\x17.kubetunnel.v1.RegisterR\bregister\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\fR\n" +
	"resultJson\"O\n" +
	"\vServerFrame\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\frequest_json\x18\x02 \x01(\fR\vrequestJson\"\xf6\x02\n" +
	"\bRegister\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\bprobe_id\x18\x02 \x01(\tR\aprobeId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\x12\x19\n" +
	"\bpod_name\x18\x05 \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\tR\tnamespace\x12+\n" +
	"\x11collector_version\x18\a \x01(\tR\x10collectorVersion\x12\x1f\n" +
	"\vk8s_version\x18\b \x01(\tR\n" +
	"k8sVersion\x12;\n" +
	"\x06labels\x18\t \x03(\v2#.kubetunnel.v1.Register.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012O\n" +
	"\x06Tunnel\x12E\n" +
	"\aConnect\x12\x1a.kubetunnel.v1.ClientFrame\x1a\x1a.kubetunnel.v1.ServerFrame(\x010\x01BTZRgithub.com/elastic/opentelemetry-collector-components/internal/kubetunnel/tunnelpbb\x06proto3"

var (
	file_tunnel_proto_rawDescOnce sync.Once
	file_tunnel_proto_rawDescData []byte
)

func file_tunnel_proto_rawDescGZIP() []byte {
	file_tunnel_proto_rawDescOnce.Do(func() {
		file_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tunnel_proto_rawDesc), len(file_tunnel_proto_rawDesc)))
	})
	return file_tunnel_proto_rawDescData
}

var file_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tunnel_proto_goTypes = []any{
	(*ClientFrame)(nil), // 0: kubetunnel.v1.ClientFrame
	(*ServerFrame)(nil), // 1: kubetunnel.v1.ServerFrame
	(*Register)(nil),    // 2: kubetunnel.v1.Register
	nil,                 // 3: kubetunnel.v1.Register.LabelsEntry
}
var file_tunnel_proto_depIdxs = []int32{
	2, // 0: kubetunnel.v1.ClientFrame.register:type_name -> kubetunnel.v1.Register
	3, // 1: kubetunnel.v1.Register.labels:type_name -> kubetunnel.v1.Register.LabelsEntry
	0, // 2: kubetunnel.v1.Tunnel.Connect:input_type -> kubetunnel.v1.ClientFrame
	1, // 3: kubetunnel.v1.Tunnel.Connect:output_type -> kubetunnel.v1.ServerFrame
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tunnel_proto_init() }
func file_tunnel_proto_init() {
	if File_tunnel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tunnel_proto_rawDesc), len(file_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tunnel_proto_goTypes,
		DependencyIndexes: file_tunnel_proto_depIdxs,
		MessageInfos:      file_tunnel_proto_msgTypes,
	}.Build()
	File_tunnel_proto = out.File
	file_tunnel_proto_goTypes = nil
	file_tunnel_proto_depIdxs = nil
}
