// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the connector/dynamicrouting component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("dynamicrouting")
	ScopeName = "github.com/elastic/opentelemetry-collector-components/connector/dynamicroutingconnector"
)

const (
	LogsToLogsStability         = component.StabilityLevelDevelopment
	MetricsToMetricsStability   = component.StabilityLevelDevelopment
	TracesToTracesStability     = component.StabilityLevelDevelopment
	ProfilesToProfilesStability = component.StabilityLevelDevelopment
)
