// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("loadgen")
	ScopeName = "github.com/elastic/opentelemetry-collector-components/receiver/loadgenreceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
	LogsStability    = component.StabilityLevelDevelopment
	TracesStability  = component.StabilityLevelDevelopment
)
