// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("elasticinframetrics")
	ScopeName = "github.com/elastic/opentelemetry-collector-components/processor/elasticinframetricsprocessor"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
