type: prometheusremotewritev1
scope_name: github.com/elastic/opentelemetry-collector-components/receiver/prometheusremotewritev1receiver
github_project: elastic/opentelemetry-collector-components

status:
  class: receiver
  stability:
    development: [metrics]
  #codeowners:
  #  active: []
