// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type = component.MustNewType("spanmetricsv2")
)

const (
	TracesToMetricsStability = component.StabilityLevelAlpha
)
