// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("elasticapm")
	ScopeName = "github.com/elastic/opentelemetry-collector-components/processor/elasticapmprocessor"
)

const (
	TracesStability  = component.StabilityLevelDevelopment
	LogsStability    = component.StabilityLevelDevelopment
	MetricsStability = component.StabilityLevelDevelopment
)
