// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("lsminterval")
	ScopeName = "github.com/elastic/opentelemetry-collector-components/processor/lsmintervalprocessor"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
