// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("elasticapm")
	ScopeName = "github.com/elastic/opentelemetry-collector-components/receiver/elasticapmreceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
	LogsStability    = component.StabilityLevelAlpha
	TracesStability  = component.StabilityLevelAlpha
)
