// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: DefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					SamplesBeamCount:         MetricConfig{Enabled: true},
					SamplesClassification:    MetricConfig{Enabled: true},
					SamplesCount:             MetricConfig{Enabled: true},
					SamplesCpythonCount:      MetricConfig{Enabled: true},
					SamplesCustomAggregation: MetricConfig{Enabled: true},
					SamplesDotnetCount:       MetricConfig{Enabled: true},
					SamplesFrameType:         MetricConfig{Enabled: true},
					SamplesGoCount:           MetricConfig{Enabled: true},
					SamplesJvmCount:          MetricConfig{Enabled: true},
					SamplesKernelCount:       MetricConfig{Enabled: true},
					SamplesNativeCount:       MetricConfig{Enabled: true},
					SamplesPerlCount:         MetricConfig{Enabled: true},
					SamplesPhpCount:          MetricConfig{Enabled: true},
					SamplesRubyCount:         MetricConfig{Enabled: true},
					SamplesRustCount:         MetricConfig{Enabled: true},
					SamplesUserCount:         MetricConfig{Enabled: true},
					SamplesV8jsCount:         MetricConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					SamplesBeamCount:         MetricConfig{Enabled: false},
					SamplesClassification:    MetricConfig{Enabled: false},
					SamplesCount:             MetricConfig{Enabled: false},
					SamplesCpythonCount:      MetricConfig{Enabled: false},
					SamplesCustomAggregation: MetricConfig{Enabled: false},
					SamplesDotnetCount:       MetricConfig{Enabled: false},
					SamplesFrameType:         MetricConfig{Enabled: false},
					SamplesGoCount:           MetricConfig{Enabled: false},
					SamplesJvmCount:          MetricConfig{Enabled: false},
					SamplesKernelCount:       MetricConfig{Enabled: false},
					SamplesNativeCount:       MetricConfig{Enabled: false},
					SamplesPerlCount:         MetricConfig{Enabled: false},
					SamplesPhpCount:          MetricConfig{Enabled: false},
					SamplesRubyCount:         MetricConfig{Enabled: false},
					SamplesRustCount:         MetricConfig{Enabled: false},
					SamplesUserCount:         MetricConfig{Enabled: false},
					SamplesV8jsCount:         MetricConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MetricConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}
