// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/connector/connectortest"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
	testDataSetReag
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "reaggregate_set",
			metricsSet:  testDataSetReag,
			resAttrsSet: testDataSetReag,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := connectortest.NewNopSettings(connectortest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))
			aggMap := make(map[string]string) // contains the aggregation strategies for each metric name
			aggMap["samples.classification"] = mb.metricSamplesClassification.config.AggregationStrategy
			aggMap["samples.custom_aggregation"] = mb.metricSamplesCustomAggregation.config.AggregationStrategy
			aggMap["samples.frame_type"] = mb.metricSamplesFrameType.config.AggregationStrategy

			expectedWarnings := 0
			if tt.metricsSet != testDataSetReag {
				assert.Equal(t, expectedWarnings, observedLogs.Len())
			}

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSamplesBeamCountDataPoint(ts, 1)

			allMetricsCount++
			mb.RecordSamplesClassificationDataPoint(ts, 1, "classification-val", "frame_type-val", "profile.type_unit-val")
			if tt.name == "reaggregate_set" {
				mb.RecordSamplesClassificationDataPoint(ts, 3, "classification-val-2", "frame_type-val-2", "profile.type_unit-val-2")
			}

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSamplesCpythonCountDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSamplesCustomAggregationDataPoint(ts, 1, "frame_type-val", "profile.type_unit-val")
			if tt.name == "reaggregate_set" {
				mb.RecordSamplesCustomAggregationDataPoint(ts, 3, "frame_type-val-2", "profile.type_unit-val-2")
			}

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSamplesDotnetCountDataPoint(ts, 1)

			allMetricsCount++
			mb.RecordSamplesFrameTypeDataPoint(ts, 1, "frame_type-val", "profile.type_unit-val")
			if tt.name == "reaggregate_set" {
				mb.RecordSamplesFrameTypeDataPoint(ts, 3, "frame_type-val-2", "profile.type_unit-val-2")
			}

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSamplesGoCountDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSamplesJvmCountDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSamplesKernelCountDataPoint(ts, 1, WithKernelAreaMetricAttribute("kernel_area-val"), WithKernelIoMetricAttribute("kernel_io-val"), WithKernelProtoMetricAttribute("kernel_proto-val"), WithSyscallNameMetricAttribute("syscall_name-val"))

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSamplesNativeCountDataPoint(ts, 1, WithShlibNameMetricAttribute("shlib_name-val"))

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSamplesPerlCountDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSamplesPhpCountDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSamplesRubyCountDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSamplesRustCountDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSamplesUserCountDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordSamplesV8jsCountDataPoint(ts, 1)

			res := pcommon.NewResource()
			metrics := mb.Emit(WithResource(res))
			if tt.name == "reaggregate_set" {
				assert.Empty(t, mb.metricSamplesClassification.aggDataPoints)
				assert.Empty(t, mb.metricSamplesCustomAggregation.aggDataPoints)
				assert.Empty(t, mb.metricSamplesFrameType.aggDataPoints)
			}

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "samples.beam.count":
					assert.False(t, validatedMetrics["samples.beam.count"], "Found a duplicate in the metrics slice: samples.beam.count")
					validatedMetrics["samples.beam.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of samples executing Beam code (self)", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityDelta, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "samples.classification":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["samples.classification"], "Found a duplicate in the metrics slice: samples.classification")
						validatedMetrics["samples.classification"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Number of profiling frames by classification", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						classificationAttrVal, ok := dp.Attributes().Get("classification")
						assert.True(t, ok)
						assert.Equal(t, "classification-val", classificationAttrVal.Str())
						frameTypeAttrVal, ok := dp.Attributes().Get("frame_type")
						assert.True(t, ok)
						assert.Equal(t, "frame_type-val", frameTypeAttrVal.Str())
						profileTypeUnitAttrVal, ok := dp.Attributes().Get("profile.type_unit")
						assert.True(t, ok)
						assert.Equal(t, "profile.type_unit-val", profileTypeUnitAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["samples.classification"], "Found a duplicate in the metrics slice: samples.classification")
						validatedMetrics["samples.classification"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Number of profiling frames by classification", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["samples.classification"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("classification")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("frame_type")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("profile.type_unit")
						assert.False(t, ok)
					}
				case "samples.cpython.count":
					assert.False(t, validatedMetrics["samples.cpython.count"], "Found a duplicate in the metrics slice: samples.cpython.count")
					validatedMetrics["samples.cpython.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of samples executing Python code (self)", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityDelta, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "samples.custom_aggregation":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["samples.custom_aggregation"], "Found a duplicate in the metrics slice: samples.custom_aggregation")
						validatedMetrics["samples.custom_aggregation"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Number of profiling frames by classification", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						frameTypeAttrVal, ok := dp.Attributes().Get("frame_type")
						assert.True(t, ok)
						assert.Equal(t, "frame_type-val", frameTypeAttrVal.Str())
						profileTypeUnitAttrVal, ok := dp.Attributes().Get("profile.type_unit")
						assert.True(t, ok)
						assert.Equal(t, "profile.type_unit-val", profileTypeUnitAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["samples.custom_aggregation"], "Found a duplicate in the metrics slice: samples.custom_aggregation")
						validatedMetrics["samples.custom_aggregation"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Number of profiling frames by classification", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["samples.custom_aggregation"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("frame_type")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("profile.type_unit")
						assert.False(t, ok)
					}
				case "samples.dotnet.count":
					assert.False(t, validatedMetrics["samples.dotnet.count"], "Found a duplicate in the metrics slice: samples.dotnet.count")
					validatedMetrics["samples.dotnet.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of samples executing Dotnet code (self)", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityDelta, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "samples.frame_type":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["samples.frame_type"], "Found a duplicate in the metrics slice: samples.frame_type")
						validatedMetrics["samples.frame_type"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Number of profiles frames by frame type", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						frameTypeAttrVal, ok := dp.Attributes().Get("frame_type")
						assert.True(t, ok)
						assert.Equal(t, "frame_type-val", frameTypeAttrVal.Str())
						profileTypeUnitAttrVal, ok := dp.Attributes().Get("profile.type_unit")
						assert.True(t, ok)
						assert.Equal(t, "profile.type_unit-val", profileTypeUnitAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["samples.frame_type"], "Found a duplicate in the metrics slice: samples.frame_type")
						validatedMetrics["samples.frame_type"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Number of profiles frames by frame type", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["samples.frame_type"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("frame_type")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("profile.type_unit")
						assert.False(t, ok)
					}
				case "samples.go.count":
					assert.False(t, validatedMetrics["samples.go.count"], "Found a duplicate in the metrics slice: samples.go.count")
					validatedMetrics["samples.go.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of samples executing Go code (self)", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityDelta, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "samples.jvm.count":
					assert.False(t, validatedMetrics["samples.jvm.count"], "Found a duplicate in the metrics slice: samples.jvm.count")
					validatedMetrics["samples.jvm.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of samples executing HotSpot code (self)", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityDelta, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "samples.kernel.count":
					assert.False(t, validatedMetrics["samples.kernel.count"], "Found a duplicate in the metrics slice: samples.kernel.count")
					validatedMetrics["samples.kernel.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of samples executing kernel code (self)", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityDelta, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					kernelAreaAttrVal, ok := dp.Attributes().Get("kernel_area")
					assert.True(t, ok)
					assert.Equal(t, "kernel_area-val", kernelAreaAttrVal.Str())
					kernelIoAttrVal, ok := dp.Attributes().Get("kernel_io")
					assert.True(t, ok)
					assert.Equal(t, "kernel_io-val", kernelIoAttrVal.Str())
					kernelProtoAttrVal, ok := dp.Attributes().Get("kernel_proto")
					assert.True(t, ok)
					assert.Equal(t, "kernel_proto-val", kernelProtoAttrVal.Str())
					syscallNameAttrVal, ok := dp.Attributes().Get("syscall_name")
					assert.True(t, ok)
					assert.Equal(t, "syscall_name-val", syscallNameAttrVal.Str())
				case "samples.native.count":
					assert.False(t, validatedMetrics["samples.native.count"], "Found a duplicate in the metrics slice: samples.native.count")
					validatedMetrics["samples.native.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of samples executing native code (self)", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityDelta, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					shlibNameAttrVal, ok := dp.Attributes().Get("shlib_name")
					assert.True(t, ok)
					assert.Equal(t, "shlib_name-val", shlibNameAttrVal.Str())
				case "samples.perl.count":
					assert.False(t, validatedMetrics["samples.perl.count"], "Found a duplicate in the metrics slice: samples.perl.count")
					validatedMetrics["samples.perl.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of samples executing Perl code (self)", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityDelta, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "samples.php.count":
					assert.False(t, validatedMetrics["samples.php.count"], "Found a duplicate in the metrics slice: samples.php.count")
					validatedMetrics["samples.php.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of samples executing PHP code (self)", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityDelta, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "samples.ruby.count":
					assert.False(t, validatedMetrics["samples.ruby.count"], "Found a duplicate in the metrics slice: samples.ruby.count")
					validatedMetrics["samples.ruby.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of samples executing Ruby code (self)", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityDelta, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "samples.rust.count":
					assert.False(t, validatedMetrics["samples.rust.count"], "Found a duplicate in the metrics slice: samples.rust.count")
					validatedMetrics["samples.rust.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of samples executing Rust code (self)", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityDelta, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "samples.user.count":
					assert.False(t, validatedMetrics["samples.user.count"], "Found a duplicate in the metrics slice: samples.user.count")
					validatedMetrics["samples.user.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of samples executing userspace code (self)", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityDelta, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "samples.v8js.count":
					assert.False(t, validatedMetrics["samples.v8js.count"], "Found a duplicate in the metrics slice: samples.v8js.count")
					validatedMetrics["samples.v8js.count"] = true
					assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
					assert.Equal(t, 1, mi.Sum().DataPoints().Len())
					assert.Equal(t, "Number of samples executing v8js code (self)", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					assert.True(t, mi.Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityDelta, mi.Sum().AggregationTemporality())
					dp := mi.Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				}
			}
		})
	}
}
