// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for profilingmetrics metrics.
type MetricsConfig struct {
	SamplesBeamCount         MetricConfig `mapstructure:"samples.beam.count"`
	SamplesClassification    MetricConfig `mapstructure:"samples.classification"`
	SamplesCount             MetricConfig `mapstructure:"samples.count"`
	SamplesCpythonCount      MetricConfig `mapstructure:"samples.cpython.count"`
	SamplesCustomAggregation MetricConfig `mapstructure:"samples.custom_aggregation"`
	SamplesDotnetCount       MetricConfig `mapstructure:"samples.dotnet.count"`
	SamplesFrameType         MetricConfig `mapstructure:"samples.frame_type"`
	SamplesGoCount           MetricConfig `mapstructure:"samples.go.count"`
	SamplesJvmCount          MetricConfig `mapstructure:"samples.jvm.count"`
	SamplesKernelCount       MetricConfig `mapstructure:"samples.kernel.count"`
	SamplesNativeCount       MetricConfig `mapstructure:"samples.native.count"`
	SamplesPerlCount         MetricConfig `mapstructure:"samples.perl.count"`
	SamplesPhpCount          MetricConfig `mapstructure:"samples.php.count"`
	SamplesRubyCount         MetricConfig `mapstructure:"samples.ruby.count"`
	SamplesRustCount         MetricConfig `mapstructure:"samples.rust.count"`
	SamplesUserCount         MetricConfig `mapstructure:"samples.user.count"`
	SamplesV8jsCount         MetricConfig `mapstructure:"samples.v8js.count"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		SamplesBeamCount: MetricConfig{
			Enabled: true,
		},
		SamplesClassification: MetricConfig{
			Enabled: true,
		},
		SamplesCount: MetricConfig{
			Enabled: true,
		},
		SamplesCpythonCount: MetricConfig{
			Enabled: true,
		},
		SamplesCustomAggregation: MetricConfig{
			Enabled: true,
		},
		SamplesDotnetCount: MetricConfig{
			Enabled: true,
		},
		SamplesFrameType: MetricConfig{
			Enabled: true,
		},
		SamplesGoCount: MetricConfig{
			Enabled: true,
		},
		SamplesJvmCount: MetricConfig{
			Enabled: true,
		},
		SamplesKernelCount: MetricConfig{
			Enabled: true,
		},
		SamplesNativeCount: MetricConfig{
			Enabled: true,
		},
		SamplesPerlCount: MetricConfig{
			Enabled: true,
		},
		SamplesPhpCount: MetricConfig{
			Enabled: true,
		},
		SamplesRubyCount: MetricConfig{
			Enabled: true,
		},
		SamplesRustCount: MetricConfig{
			Enabled: true,
		},
		SamplesUserCount: MetricConfig{
			Enabled: true,
		},
		SamplesV8jsCount: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for profilingmetrics metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}
