// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					SamplesBeamCount: SamplesBeamCountMetricConfig{
						Enabled: true,
					},
					SamplesClassification: SamplesClassificationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SamplesClassificationMetricAttributeKey{SamplesClassificationMetricAttributeKeyClassification, SamplesClassificationMetricAttributeKeyFrameType, SamplesClassificationMetricAttributeKeyProfileTypeUnit},
					},
					SamplesCpythonCount: SamplesCpythonCountMetricConfig{
						Enabled: true,
					},
					SamplesCustomAggregation: SamplesCustomAggregationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SamplesCustomAggregationMetricAttributeKey{SamplesCustomAggregationMetricAttributeKeyFrameType, SamplesCustomAggregationMetricAttributeKeyProfileTypeUnit},
					},
					SamplesDotnetCount: SamplesDotnetCountMetricConfig{
						Enabled: true,
					},
					SamplesFrameType: SamplesFrameTypeMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SamplesFrameTypeMetricAttributeKey{SamplesFrameTypeMetricAttributeKeyFrameType, SamplesFrameTypeMetricAttributeKeyProfileTypeUnit},
					},
					SamplesGoCount: SamplesGoCountMetricConfig{
						Enabled: true,
					},
					SamplesJvmCount: SamplesJvmCountMetricConfig{
						Enabled: true,
					},
					SamplesKernelCount: SamplesKernelCountMetricConfig{
						Enabled: true,
					},
					SamplesNativeCount: SamplesNativeCountMetricConfig{
						Enabled: true,
					},
					SamplesPerlCount: SamplesPerlCountMetricConfig{
						Enabled: true,
					},
					SamplesPhpCount: SamplesPhpCountMetricConfig{
						Enabled: true,
					},
					SamplesRubyCount: SamplesRubyCountMetricConfig{
						Enabled: true,
					},
					SamplesRustCount: SamplesRustCountMetricConfig{
						Enabled: true,
					},
					SamplesUserCount: SamplesUserCountMetricConfig{
						Enabled: true,
					},
					SamplesV8jsCount: SamplesV8jsCountMetricConfig{
						Enabled: true,
					},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					SamplesBeamCount: SamplesBeamCountMetricConfig{
						Enabled: false,
					},
					SamplesClassification: SamplesClassificationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SamplesClassificationMetricAttributeKey{SamplesClassificationMetricAttributeKeyClassification, SamplesClassificationMetricAttributeKeyFrameType, SamplesClassificationMetricAttributeKeyProfileTypeUnit},
					},
					SamplesCpythonCount: SamplesCpythonCountMetricConfig{
						Enabled: false,
					},
					SamplesCustomAggregation: SamplesCustomAggregationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SamplesCustomAggregationMetricAttributeKey{SamplesCustomAggregationMetricAttributeKeyFrameType, SamplesCustomAggregationMetricAttributeKeyProfileTypeUnit},
					},
					SamplesDotnetCount: SamplesDotnetCountMetricConfig{
						Enabled: false,
					},
					SamplesFrameType: SamplesFrameTypeMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []SamplesFrameTypeMetricAttributeKey{SamplesFrameTypeMetricAttributeKeyFrameType, SamplesFrameTypeMetricAttributeKeyProfileTypeUnit},
					},
					SamplesGoCount: SamplesGoCountMetricConfig{
						Enabled: false,
					},
					SamplesJvmCount: SamplesJvmCountMetricConfig{
						Enabled: false,
					},
					SamplesKernelCount: SamplesKernelCountMetricConfig{
						Enabled: false,
					},
					SamplesNativeCount: SamplesNativeCountMetricConfig{
						Enabled: false,
					},
					SamplesPerlCount: SamplesPerlCountMetricConfig{
						Enabled: false,
					},
					SamplesPhpCount: SamplesPhpCountMetricConfig{
						Enabled: false,
					},
					SamplesRubyCount: SamplesRubyCountMetricConfig{
						Enabled: false,
					},
					SamplesRustCount: SamplesRustCountMetricConfig{
						Enabled: false,
					},
					SamplesUserCount: SamplesUserCountMetricConfig{
						Enabled: false,
					},
					SamplesV8jsCount: SamplesV8jsCountMetricConfig{
						Enabled: false,
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(SamplesBeamCountMetricConfig{}, SamplesClassificationMetricConfig{}, SamplesCpythonCountMetricConfig{}, SamplesCustomAggregationMetricConfig{}, SamplesDotnetCountMetricConfig{}, SamplesFrameTypeMetricConfig{}, SamplesGoCountMetricConfig{}, SamplesJvmCountMetricConfig{}, SamplesKernelCountMetricConfig{}, SamplesNativeCountMetricConfig{}, SamplesPerlCountMetricConfig{}, SamplesPhpCountMetricConfig{}, SamplesRubyCountMetricConfig{}, SamplesRustCountMetricConfig{}, SamplesUserCountMetricConfig{}, SamplesV8jsCountMetricConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func TestSamplesClassificationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SamplesClassification
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SamplesClassificationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric samples.classification doesn't have an attribute invalid, valid attributes: [classification, frame_type, profile.type_unit]")

	cfg = DefaultMetricsConfig().SamplesClassification
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSamplesCustomAggregationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SamplesCustomAggregation
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SamplesCustomAggregationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric samples.custom_aggregation doesn't have an attribute invalid, valid attributes: [frame_type, profile.type_unit]")

	cfg = DefaultMetricsConfig().SamplesCustomAggregation
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestSamplesFrameTypeMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().SamplesFrameType
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []SamplesFrameTypeMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric samples.frame_type doesn't have an attribute invalid, valid attributes: [frame_type, profile.type_unit]")

	cfg = DefaultMetricsConfig().SamplesFrameType
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}
