run-name: release-otelbench
name: Release otelbench docker image on elastic container library

on:
  push:
    branches:
      - main
    paths:
      - ./loadgen/cmd/otelbench/CHANGELOG.md

permissions:
  contents: read

jobs:
  release-otelbench:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ELASTIC_REGISTRY: "docker.elastic.co/observability-ci"
      IMAGE_NAME: "otelbench"
    steps:
      - uses: actions/checkout@v4

      - name: Login to Elastic container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.ELASTIC_REGISTRY }}
          username: ${{ secrets.ELASTIC_DOCKER_USERNAME }}
          password: ${{ secrets.ELASTIC_DOCKER_PASSWORD }}

      - name: Get otelbench version
        working-directory: ./loadgen/cmd/otelbench
        run: echo "OTELBENCH_VERSION=$(make get-version 2>/dev/null || echo 'v0.0.0')" >> $GITHUB_ENV

      - uses: ko-build/setup-ko@d982fec422852203cfb2053a8ec6ad302280d04d
        env:
          KO_DOCKER_REPO: ${{ env.ELASTIC_REGISTRY }}

      - name: Build container image and push to Elastic registry
        working-directory: ./loadgen/cmd/otelbench
        run: |
          export KO_DOCKER_REPO=${{ env.ELASTIC_REGISTRY }}
          local_platform="linux/$(go env GOARCH)"
          KO_IMAGE=$(ko build --platform=$local_platform)
          docker tag "$KO_IMAGE" "${{ env.ELASTIC_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.OTELBENCH_VERSION }}"