name: release-otelbench
run-name: Release otelbench docker image on elastic container library

on:
  push:
    branches:
      - main
    paths:
      - loadgen/cmd/otelbench/CHANGELOG.md

  # TODO Please remove this once
  # it is clear that the push trigger
  # works
  workflow_dispatch:


permissions:
  contents: read

jobs:
  release-otelbench:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ELASTIC_REGISTRY: "docker.elastic.co/observability-ci/otelbench"
    steps:
      - uses: actions/checkout@v4

      - name: Login to Elastic container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ env.ELASTIC_REGISTRY }}
          username: ${{ secrets.ELASTIC_DOCKER_USERNAME }}
          password: ${{ secrets.ELASTIC_DOCKER_PASSWORD }}

      - name: Get otelbench version
        working-directory: ./loadgen/cmd/otelbench
        run: echo "OTELBENCH_VERSION=$(make get-version 2>/dev/null || echo 'v0.0.0')" >> $GITHUB_ENV

      - uses: ko-build/setup-ko@d982fec422852203cfb2053a8ec6ad302280d04d # v0.8
        env:
          KO_DOCKER_REPO: ${{ env.ELASTIC_REGISTRY }}

      - name: Build container image and push to Elastic registry
        working-directory: ./loadgen/cmd/otelbench
        run: |
          export KO_DOCKER_REPO=${{ env.ELASTIC_REGISTRY }}
          local_platform="linux/$(go env GOARCH)"
          ko build --bare --platform=$local_platform --tags ${{ env.OTELBENCH_VERSION }}"